ads/accounts/urls.py
from django.urls import path, re_path
from . import views as accounts_views
from .views import ProfileDetailView, ProfileEditView

app_name = 'accounts'

urlpatterns = [
    path('signup/', accounts_views.signup, name='signup'),
    re_path(r'^(?P<pk>\d+)/*$', ProfileDetailView.as_view(), name='profile'),
    re_path(r'^(?P<pk>\d+)/edit/*$', ProfileEditView.as_view(), name='profile_edit')


]

ads/ads/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bulletin_board.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ads/templates/ad.html
{% extends 'base.html' %}

{% block title %} Advertisement {% endblock title %}

{% block content %}
<h2>{{ advertisement.title }}</h2>
<div class="ad__item_wrapper">

    <img class="ad__item_picture" src="{{advertisement.picture.url}}">

    <div class="ad__item_info">
<p> {{advertisement.publication_date|date:"d F Y"}}</p>
<p>{{ advertisement.content}}</p>
<p>Price: {{advertisement.price}} rub.</p>
        <p><a href="{% url 'accounts:profile' advertisement.author.id %}">{{advertisement.author}} </a>
            Phone: {{advertisement.author.phone}} </p>
    </div>

</div>
<a class="button" href="{% url 'category' advertisement.category.id %}">List</a>



{% if advertisement.author == user %}
<p>
<a class="button" href="{% url 'ad_edit' advertisement.id %}">Edit</a>
<a  class="button" href="{% url 'ad_delete' advertisement.id %}">Delete</a>
    <a  class="button" href="{% url 'accounts:profile' advertisement.author.id %}">Profile</a>
</p>
{% endif %}

{%endblock content%}

ads/templates/ad_creation.html
{% extends 'base.html' %}

{% block title %} Advertisement creation {% endblock title %}

{% block content %}

<h1>Advertisement creation</h1>

<form method="POST" action=""  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input  class="button" type="submit" value="Create">
    <p><a class="button" href="{{request.META.HTTP_REFERER}}">Go back</a></p>
</form>

{%endblock content%}

ads/templates/ad_delete.html
{% extends 'base.html' %}

{% block title %} Ad delete {% endblock title %}

{% block content %}

<h1>Delete advertisement</h1>

<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete the advertisement "{{advertisement.title}}"?</p>
    <input  class="button" type="submit" value="Confirm">
    <p><a class="button" href="{{request.META.HTTP_REFERER}}">Cancel</a></p>
</form>

{%endblock content%}

ads/templates/ad_edit.html
{% extends 'base.html' %}

{% block title %} Ad edit {% endblock title %}

{% block content %}

<h1>Edit advertisement</h1>

<form method="POST" action=""  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="button" type="submit" value="Update">
    <p><a class="button" href="{% url 'ad' advertisement.id %}">Cancel</a></p>
</form>


{%endblock content%}

ads/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet"  type="text/css" href=" {% static 'bulletin_board/css/common.css' %} ">
    <link rel="stylesheet"  type="text/css" href=" {% static 'bulletin_board/css/category.css' %} ">
     <link rel="stylesheet"  type="text/css" href=" {% static 'accounts/css/profile.css' %} ">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Quintessential&family=Roboto&display=swap" rel="stylesheet">


    <title >{% block title %} Document {% endblock title %} </title>
</head>
<body>
    {% block header %}
    <header class="header wrapper">
        <div class="header__logo"><a href="{% url 'index' %}">Bulletin board </a></div>
        <div class="header__user_info">
        {% if user.is_authenticated %}
        <p class="header__user_name">{{user.first_name}} {{user.last_name}}</p>
            <div class="header__user_auth">
        <a href = "{% url 'accounts:profile' user.id %}"> Profile </a>
         <a href = "{% url 'logout' %}"> LogOut </a>
            <a href="{% url 'index'%}">Home</a>
            </div>
        {% else %}
        <p class="header__user_name">You are not logged in.</p>
           <div class="header__user_auth"> <a href = "{% url 'login' %}"> LogIn </a>
        <a href = "{% url 'accounts:signup' %}"> SignUp </a>
           <a href="{% url 'index'%}">Home</a>
           </div>
        {% endif %}
        </div>
    </header>
    {% endblock header %}
    <main class="wrapper" >

        {% block content %}
        {%endblock content%}
    </main>
    <footer class="footer">
        <p>Copyright © Denis Efremov</p>
    </footer>
</body>
</html>

ads/templates/category.html
{% extends 'base.html' %}

{% block title %} Category {% endblock title %}

{% block content %}
<form method="GET" action="" >
    {% csrf_token %}
    <div class="form__filter_wrapper">
    <div>  {{ filter_form.sort_type_choice.label }} {{ filter_form.sort_type_choice }}</div>
    <div>{{ filter_form.max_price_choice.label }} {{ filter_form.max_price_choice }}</div>
    <div>{{ filter_form.region_choice.label }} {{ filter_form.region_choice }}</div>
    <input type="submit" value="Apply" class="button">
        </div>
</form>

<h2>{{ category_item.name }} in  {{region}} </h2>
  {% if ad_list %}
  <ul>
    {% for ad in ad_list %}
    <li>
        <div class="ad__item_wrapper">
            {% if ad.picture %}
            <div > <a href = "{%url 'ad' ad.id %}"><img  class="ad__item_picture" src="{{ad.picture.url}}"></a> </div>
            {% endif %}
            <div class="ad__item_info">
        <a href = "{%url 'ad' ad.id %}">{{ ad.title }}</a>
            <p> {{ad.publication_date}} </p>
        <p>Price: {{ad.price}}<p>
        <p>{{ad.author.region}}</p>
            <p><a href="{% url 'accounts:profile' ad.author.id %}">{{ad.author.first_name}}
                {{ad.author.last_name}}</a> Phone: {{ad.author.phone}} </p>
            </div>
        </div>
        <hr>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No advertisments</p>
  {% endif %}

<!--====Pagination====-->
{% if ad_list.has_other_pages %}
<ul class="pagination">
    {% if ad_list.has_previous %}
        <li><a href="?page={{ ad_list.previous_page_number }}{{request_string}}">previous page</a></li>
    {% else %}
        <li class="disabled">previous page</li>
    {% endif %}
    {% for item_page in ad_list.paginator.page_range %}
        {% if ad_list.number == item_page %}
            <li class="active">{{ item_page }}</li>
        {% else %}
            <li><a href="?page={{ item_page }}{{request_string}}">{{ item_page }}</a></li>
        {% endif %}
    {% endfor %}
    {% if ad_list.has_next %}
        <li><a href="?page={{ ad_list.next_page_number }}{{request_string}}">next page</a></li>
    {% else %}
        <li class="disabled">previous page</li>
    {% endif %}
</ul>
{% endif %}

<p><a class="button" href="{% url 'index' %}">Back to categories</a></p>
{%endblock content%}

ads/templates/index.html
{% extends 'base.html' %}

{% block title %} Bulletin board {% endblock title %}

{% block content %}
  <h2>Categories</h2>
  <ul>
    {% for category in category_list %}
    <li><a href="{% url 'category' category.id %}">{{ category.name }}</a></li>
    {% endfor %}
  </ul>

{% endblock content %}

ads/templates/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}
<h2> Profile of {{ object.first_name }} {{ object.last_name}}</h2>
<p>Name: {{ object.first_name }} </p>
<p>Last name: {{ object.last_name }}</p>
<p> Region: {{ object.region }}</p>
<p> Phone: {{object.phone}}</p>
<p> Email: {{object.email}}</p>

{% if object.avatar %}
<p>Avatar: <img class="profile__avatar" src="{{object.avatar.url}}"> </p>
{% endif %}
<p><a class="button"  href="{% url 'index'%}">Back to categories</a></p>

{% if object.id == user.id  and user.is_authenticated %}
<p ><a class="button" href="{% url 'accounts:profile_edit' object.id %} ">Edit profile</a></p>
<p ><a class="button" href="{% url 'ad_create' %} ">Create new advertisement</a></p>
<p><a class="button" href="{% url 'ad_list' %}">My advertisements</a></p>

{% endif %}

{%endblock content%}

ads/templates/profile_edit.html
{% extends 'base.html' %}

{% block title %} Profile edit {% endblock title %}

{% block content %}

<h1>Profile edit</h1>

<form method="POST" action=""  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="button" type="submit" value="Update">
    <p><a class="button" href = "{% url 'accounts:profile' user.id %}"> Cancel </a></p>
</form>


{%endblock content%}

ads/templates/user_ad.html
{% extends 'base.html' %}

{% block title %} User`s ads {% endblock title %}

{% block content %}
  <h2>Advertisements of {{user.first_name}}</h2>
{% if ad_list %}
  <ul>
    {% for ad in ad_list %}
    <li>
      <p><a href="{% url 'ad' ad.id %}">{{ ad.title }}</a></p>
      <a class="button" href="{% url 'ad_edit' ad.id %}">Edit</a>
      <a class="button" href="{% url 'ad_delete' ad.id %}">Delete</a>
    </li>
    <hr>
    {% endfor %}
  </ul>
  {% else %}
  <p>You don't have any advertisements</p>
  {% endif %}
<a  class="button" href="{% url 'accounts:profile' user.id %}">Back to profile</a>

{% endblock content %}